---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: ocm-update-cron
  name: ocm-update-cron
spec:
  output:
    to:
      kind: ImageStreamTag
      name: ocm-update-cron:1.0
  runPolicy: Serial
  source:
    type: Git
    git:
      ref: master
      uri: https://github.com/thuyn-581/openshift-cronjob.git
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python:3.6
        namespace: openshift
